apiVersion: apps/v1
kind: Deployment
metadata:
  name: syslog-srv
  namespace: syslog-srv
  labels:
    name: syslog-srv
spec:
  selector:
    matchLabels:
      name: syslog-srv
  replicas: 1
  template:
    metadata:
      namespace: syslog-srv
      labels:
        name: syslog-srv
    spec:
      containers:
      - name: syslog-srv
        image: hasitha84/syslogsrv:latest
        command: ["/usr/local/bin/raftman"]
        args: ["-frontend syslog+udp://:4514?format=RFC5424&queueSize=512&timeout=0s"]
        resources:
          requests:
            cpu: 500m
            memory: 128Mi
        ports:
        - name: syslog-udp
          containerPort: 4514
          protocol: UDP
        - name: syslog-tcp
          containerPort: 5514
        - name: api
          containerPort: 8181
        - name: web
          containerPort: 8282
