apiVersion: apps/v1
kind: Deployment
metadata:
  name: syslog-srv
  namespace: syslog-srv
  labels:
    name: syslog-srv
spec:
  selector:
    matchLabels:
      name: syslog-srv
  replicas: 1
  template:
    metadata:
      namespace: syslog-srv
      labels:
        name: syslog-srv
    spec:
      containers:
      - name: syslog-srv
        image: hasitha84/syslogsrv:latest
        resources:
          requests:
            cpu: 500m
            memory: 128Mi
        ports:
        - name: syslog-udp
          containerPort: 5514
          protocol: UDP
        - name: syslog-tcp
          containerPort: 5514
        - name: http
          containerPort: 8181
        - name: https
          containerPort: 8282
