apiVersion: v1
kind: Service
metadata:
  labels:
    name: syslog-srv-tcp-svc
  name: syslog-srv-tcp-svc
  namespace: syslog-srv
  annotations:
    metallb.universe.tf/allow-shared-ip: syslog-srv
spec:
  type: LoadBalancer
  # loadBalancerIP is optional. MetalLB will automatically allocate an IP 
  # from its pool if not specified. You can also specify one manually.
  loadBalancerIP: 192.168.1.14
  ports:
  - name: syslog-tcp
    port: 514
    targetPort: 5514
    protocol: TCP
  - name: http
    port: 8181
    protocol: TCP
  - name: https
    port: 8282
    protocol: TCP
  selector:
    name: syslog-srv

---

apiVersion: v1
kind: Service
metadata:
  labels:
    name: syslog-srv-udp-svc
  name: syslog-srv-udp-svc
  namespace: syslog-srv
  annotations:
    metallb.universe.tf/allow-shared-ip: syslog-srv
spec:
  type: LoadBalancer
  # loadBalancerIP is optional. MetalLB will automatically allocate an IP 
  # from its pool if not specified. You can also specify one manually.
  loadBalancerIP: 192.168.1.14
  ports:
  - name: syslog-udp
    port: 514
    targetPort: 5514
  selector:
    name: syslog-srv