apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-controller
  namespace: unifi
  labels:
    name: unifi-controller
spec:
  selector:
    matchLabels:
      name: unifi-controller
  replicas: 1
  template:
    metadata:
      namespace: unifi
      labels:
        name: unifi-controller
    spec:
      containers:
      - name: unifi-controller
        image: linuxserver/unifi-controller:version-6.1.71
        resources:
          requests:
            cpu: 500m
            memory: 128Mi
        env:
        - name: PUID
          value: "1001"
        - name: PGID
          value: "1001"
        - name: TZ
          value: "Europe/London"
        ports:
        - name: stun
          containerPort: 3478
          protocol: UDP
        - name: ap-discovery
          containerPort: 10001
          protocol: UDP
        - name: device-comm
          containerPort: 8080
        - name: unifi-web
          containerPort: 8443
        - name: ctrl-discovery
          containerPort: 1900
          protocol: UDP
        - name: guest-https
          containerPort: 8843
        - name: guest-http
          containerPort: 8880
        - name: througput-test
          containerPort: 6789
        - name: remote-syslog
          containerPort: 5514
          protocol: UDP
        volumeMounts:
        - name: unifi-data-volume
          mountPath: "/config"
      volumes:
      - name: unifi-data-volume
        persistentVolumeClaim:
          claimName: unifi-controller
