apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-controller
  namespace: unifi
  labels:
    name: unifi-controller
spec:
  selector:
    matchLabels:
      name: unifi-controller
  replicas: 1
  template:
    metadata:
      namespace: unifi
      labels:
        name: unifi-controller
    spec:
      containers:
      - name: unifi-controller
        image: linuxserver/unifi-controller:version-6.0.45
        # image: gcr.io/google-samples/gb-frontend:v4
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: PUID
          value: "1001"
        - name: PGID
          value: "1001"
        - name: TZ
          value: "Europe/London"
        ports:
        - name: stun
          containerPort: 3478
        - name: ap-discovery
          containerPort: 10001
        - name: device-comm
          containerPort: 8080
        - name: unifi-web
          containerPort: 8443
        volumeMounts:
        - name: unifi-data-volume
          mountPath: "/config"
      volumes:
      - name: unifi-data-volume
        persistentVolumeClaim:
          claimName: unifi-controller
