apiVersion: v1
kind: Service
metadata:
  labels:
    name: homebridge-http
  name: homebridge-http
  namespace: homebridge
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
  selector:
    name: homebridge
