apiVersion: v1
kind: Service
metadata:
  labels:
    name: homebridge-ui
  name: homebridge-ui
  namespace: homebridge
  annotations:
    metallb.universe.tf/allow-shared-ip: homebridge
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.14
  ports:
  - name: ui
    port: 80
    targetPort: 8581
  selector:
    name: homebridge

---

apiVersion: v1
kind: Service
metadata:
  labels:
    name: homebridge-bridge
  name: homebridge-bridge
  namespace: homebridge
  annotations:
    metallb.universe.tf/allow-shared-ip: homebridge
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.14
  ports:
  - name: bridge
    port: 52405
    targetPort: 52405
  selector:
    name: homebridge