apiVersion: v1
kind: Service
metadata:
  labels:
    name: homebridge-http
  name: homebridge-http
  namespace: homebridge
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.14
  ports:
  - name: http
    port: 80
    targetPort: 8581
  selector:
    name: homebridge
